shared:
    image: node:8
jobs:
    main:
        requires: [~pr, ~commit]
        steps:
            - s1: echo "Hello"
            - s2: echo "World"
    deploy:
        requires: main
        freezeWindows: ['45 19 * * *']
        image: node:8
        environment:
            DEPLOY_ENV: dev
        steps:
            - init: echo $DEPLOY_ENV
            - deploy: echo "deploy"
        annotations:
            # screwdriver.cd/timeout: 1
            screwdriver.cd/buildPeriodically: "*/10 * * * *"
