shared:
    image: node:8
    settings:
        slack:
            channels:
                - 'local-builds'
            statuses:
                - SUCCESS
                - FAILURE
                - ABORTED
                - QUEUED
                - RUNNING
jobs:
    main:
        requires: [~pr, ~commit]
        steps:
            - s1: echo "Hello"
            - s2: echo "World"
    deploy:
        requires: main
        image: node:8
        environment:
            DEPLOY_ENV: dev
        steps:
            - init: echo $DEPLOY_ENV
            - wait: sleep 2m
            - deploy: echo "deploy"
        # freezeWindows:
        #     - "* 0-10 ? * 1,5-6"
        annotations:
            screwdriver.cd/timeout: 1
            screwdriver.cd/buildPeriodically: "H(20-20) * * * *"

    test:
        requires: deploy
        image: node:12
        steps:
            - init: echo 'init'
            - test: echo "test"
        freezeWindows:
            - "* 0-18 ? * MON"

    publish:
        requires: deploy
        steps:
            - echo-hello: echo hello
            - wait: sleep 4m
        freezeWindows:
            - "* 0-18 ? * TUE,WED"
        annotations:
            screwdriver.cd/timeout: 2
            screwdriver.cd/buildPeriodically: "H(50-55) * * * *"
    publish1:
        steps:
            - echo-hello: echo hello
        requires: ~commit
        annotations:
            # screwdriver.cd/timeout: 1
            screwdriver.cd/buildPeriodically: "H(15-30) * * * *"
    publish2:
        steps:
            - echo-hello: echo hello
            - wait: sleep 4m
        requires: ~commit
        annotations:
            screwdriver.cd/timeout: 2
            screwdriver.cd/buildPeriodically: "H(30-35) * * * *"
    publish3:
        steps:
            - echo-hello: echo hello
            - wait: sleep 4m
        requires: ~commit
        annotations:
            screwdriver.cd/timeout: 2
            # screwdriver.cd/buildPeriodically: "H * * * *"
    publish4:
        steps:
            - echo-hello: echo hello
            - wait: sleep 4m
        requires: ~commit
        annotations:
            # screwdriver.cd/timeout: 1
            screwdriver.cd/buildPeriodically: "H(10-20) * * * *"
    publish5:
        steps:
            - echo-hello: echo hello
            - wait: sleep 4m
        requires: ~commit
        annotations:
            screwdriver.cd/timeout: 4
            # screwdriver.cd/buildPeriodically: "H * * * *"
    testjob1:
        requires: ~commit
        steps:
            - start: echo "start job 1"
            - wait: sleep 1
            - stop: echo "stop job 1"
        # annotations:
            # screwdriver.cd/buildPeriodically: "H * * * *"
    testjob2:
        requires: ~commit
        steps:
            - start: echo "start job 2"
            - wait: sleep 4m
            - stop: echo "stop job 2"
        # annotations:
            # screwdriver.cd/buildPeriodically: "H(10-15) * * * *"
    testjob3:
        requires: ~commit
        steps:
            - start: echo "start job 3"
            - wait: sleep 4m
            - stop: echo "stop job 3"
        # annotations:
            # screwdriver.cd/buildPeriodically: "H(10-15) * * * *"
    testjob4:
        requires: ~commit
        steps:
            - start: echo "start job 2"
            - wait: sleep 4m
            - stop: echo "stop job 2"
        # annotations:
            # screwdriver.cd/buildPeriodically: "H(10-15) * * * *"
    testjob5:
        requires: ~commit
        steps:
            - start: echo "start job 3"
            - wait: sleep 4m
            - stop: echo "stop job 3"
        # annotations:
            # screwdriver.cd/buildPeriodically: "H(10-15) * * * *"
    testjob6:
        requires: ~commit
        steps:
            - start: echo "start job 2"
            - wait: sleep 4m
            - stop: echo "stop job 2"
        # annotations:
            # screwdriver.cd/buildPeriodically: "H(10-15) * * * *"
    testjob7:
        requires: ~commit
        steps:
            - start: echo "start job 3"
            - wait: sleep 1
            - stop: echo "stop job 3"
        # annotations:
            # screwdriver.cd/buildPeriodically: "H(10-15) * * * *"    
    testjob8:
        requires: ~commit
        steps:
            - start: echo "start job 2"
            - wait: sleep 4m
            - stop: echo "stop job 2"
        # annotations:
            # screwdriver.cd/buildPeriodically: "H(10-15) * * * *"
    testjob9:
        requires: ~commit
        steps:
            - start: echo "start job 3"
            - wait: sleep 4m
            - stop: echo "stop job 3"
        # annotations:
            # screwdriver.cd/buildPeriodically: "H(10-15) * * * *"
    testjob31:
        requires: ~commit
        steps:
            - start: echo "start job 1"
            - wait: sleep 1
            - stop: echo "stop job 1"
        # annotations:
            # screwdriver.cd/buildPeriodically: "H * * * *"
    testjob32:
        requires: ~commit
        steps:
            - start: echo "start job 2"
            - wait: sleep 4m
            - stop: echo "stop job 2"
        # annotations:
            # screwdriver.cd/buildPeriodically: "H(10-15) * * * *"
    testjob33:
        requires: ~commit
        steps:
            - start: echo "start job 3"
            - wait: sleep 4m
            - stop: echo "stop job 3"
        # annotations:
            # screwdriver.cd/buildPeriodically: "H(10-15) * * * *"
    testjob34:
        requires: ~commit
        steps:
            - start: echo "start job 2"
            - wait: sleep 4m
            - stop: echo "stop job 2"
        # annotations:
            # screwdriver.cd/buildPeriodically: "H(10-15) * * * *"
    testjob35:
        requires: ~commit
        steps:
            - start: echo "start job 3"
            - wait: sleep 4m
            - stop: echo "stop job 3"
        # annotations:
            # screwdriver.cd/buildPeriodically: "H(10-15) * * * *"
    testjob36:
        requires: ~commit
        steps:
            - start: echo "start job 2"
            - wait: sleep 4m
            - stop: echo "stop job 2"
        # annotations:
            # screwdriver.cd/buildPeriodically: "H(10-15) * * * *"
    testjob37:
        steps:
            - start: echo "start job 3"
            - wait: sleep 1
            - stop: echo "stop job 3"
        # annotations:
            # screwdriver.cd/buildPeriodically: "H(10-15) * * * *"    
    testjob38:
        requires: ~commit
        steps:
            - start: echo "start job 2"
            - wait: sleep 4m
            - stop: echo "stop job 2"
        # annotations:
            # screwdriver.cd/buildPeriodically: "H(10-15) * * * *"
    testjob39:
        requires: ~commit
        steps:
            - start: echo "start job 3"
            - wait: sleep 4m
            - stop: echo "stop job 3"
        # annotations:
            # screwdriver.cd/buildPeriodically: "H(10-15) * * * *"
    testjob10:
        requires: ~commit
        steps:
            - start: echo "start job 1"
            - wait: sleep 1
            - stop: echo "stop job 1"
        # annotations:
            # screwdriver.cd/buildPeriodically: "H * * * *"
    testjob11:
        requires: ~commit
        steps:
            - start: echo "start job 2"
            - wait: sleep 4m
            - stop: echo "stop job 2"
        # annotations:
            # screwdriver.cd/buildPeriodically: "H(10-15) * * * *"
    testjob12:
        requires: ~commit
        steps:
            - start: echo "start job 2"
            - wait: sleep 4m
            - stop: echo "stop job 2"
        # annotations:
            # screwdriver.cd/buildPeriodically: "H(10-15) * * * *"
    testjob13:
        requires: ~commit
        steps:
            - start: echo "start job 3"
            - wait: sleep 4m
            - stop: echo "stop job 3"
        # annotations:
            # screwdriver.cd/buildPeriodically: "H(10-15) * * * *"
    testjob14:
        requires: ~commit
        steps:
            - start: echo "start job 2"
            - wait: sleep 4m
            - stop: echo "stop job 2"
        # annotations:
            # screwdriver.cd/buildPeriodically: "H(10-15) * * * *"
    testjob15:
        requires: ~commit
        steps:
            - start: echo "start job 3"
            - stop: echo "stop job 3"
        # annotations:
            # screwdriver.cd/buildPeriodically: "H(10-15) * * * *"
    testjob16:
        requires: ~commit
        steps:
            - start: echo "start job 2"
            - wait: sleep 4m
            - stop: echo "stop job 2"
        # annotations:
            # screwdriver.cd/buildPeriodically: "H(10-15) * * * *"
    testjob17:
        requires: ~commit
        steps:
            - start: echo "start job 3"
            - wait: sleep 1
            - stop: echo "stop job 3"
        # annotations:
            # screwdriver.cd/buildPeriodically: "H(10-15) * * * *"    
    testjob18:
        requires: ~commit
        steps:
            - start: echo "start job 2"
            - wait: sleep 4m
            - stop: echo "stop job 2"
        # annotations:
            # screwdriver.cd/buildPeriodically: "H(10-15) * * * *"
    testjob19:
        requires: ~commit
        steps:
            - start: echo "start job 3"
            - wait: sleep 4m
            - stop: echo "stop job 3"
        # annotations:
            # screwdriver.cd/buildPeriodically: "H(10-15) * * * *"
    testjob20:
        requires: ~commit
        steps:
            - start: echo "start job 1"
            - wait: sleep 1
            - stop: echo "stop job 1"
        # annotations:
            # screwdriver.cd/buildPeriodically: "H * * * *"
    testjob21:
        requires: ~commit
        steps:
            - start: echo "start job 2"
            - wait: sleep 4m
            - stop: echo "stop job 2"
        # annotations:
            # screwdriver.cd/buildPeriodically: "H(10-15) * * * *"
    testjob22:
        requires: ~commit
        steps:
            - start: echo "start job 2"
            - wait: sleep 4m
            - stop: echo "stop job 2"
        # annotations:
            # screwdriver.cd/buildPeriodically: "H(10-15) * * * *"
    testjob23:
        requires: ~commit
        steps:
            - start: echo "start job 3"
            - wait: sleep 4m
            - stop: echo "stop job 3"
        # annotations:
            # screwdriver.cd/buildPeriodically: "H(10-15) * * * *"
    testjob24:
        requires: ~commit
        steps:
            - start: echo "start job 2"
            - wait: sleep 4m
            - stop: echo "stop job 2"
        # annotations:
            # screwdriver.cd/buildPeriodically: "H(10-15) * * * *"
    testjob25:
        requires: ~commit
        steps:
            - start: echo "start job 3"
            - wait: sleep 4m
            - stop: echo "stop job 3"
        # annotations:
            # screwdriver.cd/buildPeriodically: "H(10-15) * * * *"
    testjob26:
        requires: ~commit
        steps:
            - start: echo "start job 2"
            - wait: sleep 4m
            - stop: echo "stop job 2"
        # annotations:
            # screwdriver.cd/buildPeriodically: "H(10-15) * * * *"
    testjob27:
        steps:
            - start: echo "start job 3"
            - wait: sleep 1
            - stop: echo "stop job 3"
        # annotations:
            # screwdriver.cd/buildPeriodically: "H(10-15) * * * *"    
    testjob28:
        requires: ~commit
        steps:
            - start: echo "start job 2"
            - wait: sleep 4m
            - stop: echo "stop job 2"
        # annotations:
            # screwdriver.cd/buildPeriodically: "H(10-15) * * * *"
    testjob29:
        requires: ~commit
        steps:
            - start: echo "start job 3"
            - wait: sleep 4m
            - stop: echo "stop job 3"
        # annotations:
            # screwdriver.cd/buildPeriodically: "H(10-15) * * * *"
    testjob30:
        requires: ~commit
        steps:
            - start: echo "start job 3"
            - wait: sleep 4m
            - stop: echo "stop job 3"
        # annotations:
            # screwdriver.cd/buildPeriodically: "H(10-15) * * * *"