shared:
    image: node:8
jobs:
    main:
        requires: [~pr, ~commit]
        steps:
            - s1: echo "Hello"
            - s2: echo "World"
        #annotations: 
            #screwdriver.cd/buildPeriodically: H H(4-7) * * * 
