shared:
    image: node:8
    annotations:
        screwdriver.cd/my-cluster-annotation: cluster1-data
        screwdriver.cd/buildCluster: gq1
jobs:
    main:
        requires: [~pr, ~commit]
        steps:
            - s1: echo "Hello"
            - s2: echo "World"
    deploy:
        requires: main
        image: node:8
        environment:
            DEPLOY_ENV: dev
        steps:
            - init: echo $DEPLOY_ENV
            # - wait: sleep 3m
            - deploy: echo "deploy"
        annotations:
            # screwdriver.cd/timeout: 2 
            screwdriver.cd/buildPeriodically: H * * * *

    